# .github/workflows/ci.yml

name: C++ CI (make test)

# Trigger on any push or pull request
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Install necessary packages: cmake, build tools, and Google Test
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y cmake build-essential libgtest-dev

      # 3) Build Google Test from source and copy libraries into /usr/lib
      - name: Build & copy Google Test libraries
        run: |
          cd /usr/src/gtest
          mkdir -p build
          cd build
          cmake ..
          cmake --build . 
          sudo cp *.a /usr/lib

      # 4) Configure & build your project with CMake
      - name: Configure & build with CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release -- -j$(nproc)

      # 5) Run tests via make test
      - name: Run unit tests
        working-directory: build
        run: |
          make test
