# .github/workflows/ci.yml

name: C++ CI (make test)

# Trigger on any push or pull request
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Install necessary packages: cmake, compiler, and libgtest-dev (source only)
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y cmake build-essential libgtest-dev

      # 3) Build Google Test in /tmp/gtest_build and copy the .a files to /usr/lib
      - name: Build & install Google Test libraries
        run: |
          # Make a temporary build directory outside /usr/src/gtest
          mkdir -p /tmp/gtest_build
          cd /usr/src/gtest
          cmake . -B /tmp/gtest_build
          cmake --build /tmp/gtest_build
          # Copy the built .a files into /usr/lib so find_package(GTest) will work
          sudo cp /tmp/gtest_build/*.a /usr/lib/

      # 4) Configure and build your project with CMake
      - name: Configure & build with CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release -- -j$(nproc)

      # 5) Run tests via make test
      - name: Run unit tests
        working-directory: build
        run: |
          make test

      # 6) (Optional) Upload test logs
      # - name: Upload test logs
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test-logs
      #     path: build/Testing/Temporary/LastTest.log
